pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/binod0506devops-pixel/go-web-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t go-web-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:8080 go-web-app'
            }
        }

    }
}