pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t go-web-app .'
            }
        }

        stage('Run Container') {
            steps {
                docker stop go-web-app-container || true
                docker rm go-web-app-container || true
                sh 'docker run -d -p 8081:8080 go-web-app || true'
            }
        }

    }
}